ENABLE: [PYTHON]
ENABLE_LINTERS: [PYTHON_PYLINT]
DISABLE_LINTERS: [PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_MYPY, PYTHON_BANDIT, PYTHON_PYRIGHT, PYTHON_RUFF]
LOG_LEVEL: INFO
LINTER_RULES_PATH: /
PYTHON_PYLINT_CONFIG_FILE: .pylintrc
GITHUB_STATUS_REPORTER: true
GITHUB_COMMENT_REPORTER: true
# MARKDOWN_SUMMARY_REPORTER: false

PRE_COMMANDS:
  - command: pwd && cp requirements.txt /venvs/requirements.txt
    cwd: workspace
  - command: pwd && ls -alF && python3 -m pip install -r /venvs/requirements.txt
    venv: pylint
