name: DSA Java workflow
run-name: ${{ github.actor }}
on:
  push:
   paths:
     - dsa/java/**
env:
  CHECKOUT_PATH: 'dsa/java'

jobs:
  init-workflow:
    runs-on: ubuntu-latest
    outputs:
      checkout_path: ${{ steps.init_checkout_path.outputs.checkout_path }}
    steps:
      - name: Initialize CHECKOUT_PATH
        id: init_checkout_path
        run: echo "checkout_path=$CHECKOUT_PATH" >> $GITHUB_OUTPUT

  dsa-java-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "DSA Java workflow triggered by ${{ github.event_name }} event."
      - run: echo "Runner=${{ runner.os }}, branch=${{ github.ref }}, repo=${{ github.repository }}"
      - name: Check out code on ${{ env.CHECKOUT_PATH }}
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.CHECKOUT_PATH }}
          sparse-checkout-cone-mode: false
      - run: echo "Code checked out"
      - name: Listing files
        run: |
          ls ${{ github.workspace }}
          echo " "
          ls ${{ github.workspace }}/$CHECKOUT_PATH
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'oracle'
          cache: maven
      - run: java -version
      - name: Build with Maven
        working-directory: ./${{ env.CHECKOUT_PATH }}
        run: mvn compile

  java-lint:
    uses: ./.github/workflows/linter-java-subflow.yml
    with:
      checkout_path: ${{ needs.init-workflow.outputs.checkout_path }}
    needs: [init-workflow, dsa-java-workflow]

