name: DSA Java workflow
run-name: ${{ github.actor }}
on:
  push:
   paths:
     - dsa/java/**
jobs:
  dsa-java-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "DSA Java workflow triggered by ${{ github.event_name }} event."
      - run: echo "Runner=${{ runner.os }}, branch=${{ github.ref }}, repo=${{ github.repository }}"
      - name: Check out code on dsa/java
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'dsa/java'
          sparse-checkout-cone-mode: false
      - run: echo "Code checked out"
      - name: Listing files
        run: |
          ls ${{ github.workspace }}
          echo " "
          ls ${{ github.workspace }}/dsa/java
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'oracle'
      - run: java -version
      - run: echo "Job status is ${{ job.status }}"
