name: Subflow to perform java linter
on:
  workflow_call:
    inputs:
      checkout_path:
        description: 'The path of Java code for linting'
        required: true
        type: string
jobs:
  perform_java_lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "DSA Java workflow triggered by ${{ github.event_name }} event."
      - name: Check out code from ${{ inputs.checkout_path }}
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.checkout_path }}
          sparse-checkout-cone-mode: false
          fetch-depth: 0

      - run: echo "Code checked out"
      - name: Listing files
        run: |
          ls ${{ github.workspace }}
          echo " "
          ls ${{ github.workspace }}/${{ inputs.checkout_path }}

      - name: Run Super-linter
        uses: super-linter/super-linter@v8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_WORKING-DIRECTORY: ./${{ inputs.checkout_path }}
          DEFAULT_BRANCH: feature/githubaction1
          VALIDATE_JAVA: true
          JAVA_COMMAND_ARGS: "-c ${{ github.workspace }}/${{ inputs.checkout_path }}/checkstyle.xml"
          JAVA_JVM_COMMAND_ARGS: -Dorg.checkstyle.sun.suppressionfilter.config=./${{ inputs.checkout_path }}/checkstyle-suppressionss.xml
          # JAVA_FILE_NAME: checkstyle.xml

      - run: echo "Java linter status is ${{ job.status }}"
