name: Subflow to perform python linter
on:
  workflow_call:
    inputs:
      checkout_path:
        description: 'The path of Java code for linting'
        required: true
        type: string
      python_version:
        description: 'python version'
        required: true
        type: string

jobs:
  perform_python_lint:
    permissions:
      contents: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - run: echo "DSA Python workflow triggered by ${{ github.event_name }} event."
      - name: Check out code from ${{ inputs.checkout_path }}
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.checkout_path }}
          sparse-checkout-cone-mode: false
          fetch-depth: 0

      - run: echo "Code checked out"
      - name: Listing files
        run: |
          ls ${{ github.workspace }}
          echo " "
          ls ${{ github.workspace }}/${{ inputs.checkout_path }}

      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
      - name: Show Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        working-directory: ./${{ inputs.checkout_path }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
          pylint ./stringoperation/mintime_activate_string.py

      - name: Run Super-linter
        uses: super-linter/super-linter@v8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: ${{ github.ref_name }}
          VALIDATE_PYTHON_PYLINT: true
          LOG_LEVEL: INFO
          LINTER_RULES_PATH: /
          PYTHON_PYLINT_CONFIG_FILE: ./${{ inputs.checkout_path }}/.pylintrc

      - run: echo "Python linter status is ${{ job.status }}"

